apps/rsvp_web/lib/rsvp_web/router.ex
defmodule RsvpWeb.Router do
  use RsvpWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RsvpWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/events", EventController, :list
    get "/events/new", EventController, :create
    post "/events/new", EventController, :add
    post "/events/:id/reserve", EventController, :reserve
    get "/events/:id", EventController, :show

    get "/login", LoginController, :index
    post "/login", LoginController, :login
  end

  # Other scopes may use custom stacks.
  # scope "/api", RsvpWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: RsvpWeb.Telemetry
    end
  end
end

apps/rsvp_web/lib/rsvp_web_web/router.ex
defmodule RsvpWebWeb.Router do
  use RsvpWebWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RsvpWebWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", RsvpWebWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: RsvpWebWeb.Telemetry
    end
  end
end

apps/rsvp_web/lib/plugs/authorized_plug.ex
defmodule RsvpWeb.AuthorizedPlug do
  import Plug.Conn
  import Phoenix.Controller

  def init(opts) do
    opts
  end

  def call(conn, name) do
    user_name = conn.cookies["user_name"]

    authorize_user(conn, user_name, name)
  end

  defp authorize_user(conn, nil, _) do
    conn
    |> redirect(to: "/login")
    |> halt
  end

  defp authorize_user(conn, user_name, name) when user_name === name do
    conn
  end

  defp authorize_user(conn, _, _), do: authorize_user(conn, nil, nil)
end

apps/rsvp_web/lib/rsvp_web/controllers/event_controller.ex
defmodule RsvpWeb.EventController do
  use RsvpWeb, :controller

  plug RsvpWeb.AuthorizedPlug, "create" when action in [:create]

  def show(conn, %{"id" => id}) do
    event =
      Rsvp.EventQueries.get_by_id(id)
      |> IO.inspect()

    render(conn, "details.html", event: event)
  end

  def list(conn, _params) do
    events = Rsvp.EventQueries.get_all()
    render(conn, "list.html", events: events)
  end

  def create(conn, %{errors: errors}) do
    render(conn, "create.html", changeset: errors)
  end

  def create(conn, _params) do
    changeset = Rsvp.Events.changeset(%Rsvp.Events{}, %{})
    render(conn, "create.html", changeset: changeset)
  end

  def add(conn, %{"events" => event_params}) do
    changeset = Rsvp.Events.changeset(%Rsvp.Events{}, event_params)

    case Rsvp.EventQueries.create(changeset) do
      {:ok, %{id: id}} -> redirect(conn, to: Routes.event_path(conn, :show, id))
      {:error, reasons} -> create(conn, %{errors: reasons})
    end
  end

  def reserve(conn, %{"id" => id, "reservation" => %{"quantity" => quantity}}) do
    {:ok, event} = Rsvp.EventQueries.decrease_quantity(id, quantity)
    RsvpWeb.EventChannel.send_update(event)
    redirect(conn, to: Routes.event_path(conn, :show, id))
  end
end

apps/rsvp_web/lib/rsvp_web/controllers/login_controller.ex
defmodule RsvpWeb.LoginController do
  use RsvpWeb, :controller

  def index(conn, _) do
    render(conn, "login.html")
  end

  def login(conn, %{"login" => %{"username" => name}}) do
    expiration = 60 * 60 * 24 * 7

    conn
    |> Plug.Conn.put_resp_cookie("user_name", name, max_age: expiration)
    |> redirect(to: "/")
  end
end

apps/rsvp_web/lib/rsvp_web/controllers/page_controller.ex
defmodule RsvpWeb.PageController do
  use RsvpWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

apps/rsvp_web/lib/rsvp_web/views/error_view.ex
defmodule RsvpWeb.ErrorView do
  use RsvpWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

apps/rsvp_web/lib/rsvp_web/views/event_view.ex
defmodule RsvpWeb.EventView do
  use RsvpWeb, :view

  def format_date(date) do
    "#{date.month}/#{date.day}/#{date.year}"
  end
end

apps/rsvp_web/lib/rsvp_web/views/layout_view.ex
defmodule RsvpWeb.LayoutView do
  use RsvpWeb, :view
end

apps/rsvp_web/lib/rsvp_web/views/login_view.ex
defmodule RsvpWeb.LoginView do
  use RsvpWeb, :view
end

apps/rsvp_web/lib/rsvp_web/views/page_view.ex
defmodule RsvpWeb.PageView do
  use RsvpWeb, :view
end

apps/rsvp_web/lib/rsvp_web_web/controllers/page_controller.ex
defmodule RsvpWebWeb.PageController do
  use RsvpWebWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

apps/rsvp_web/lib/rsvp_web_web/views/error_view.ex
defmodule RsvpWebWeb.ErrorView do
  use RsvpWebWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

apps/rsvp_web/lib/rsvp_web/templates/event/create.html.eex
<h1>Add Event</h1>
<%= form_for @changeset, Routes.event_path(@conn, :add), fn f -> %>
<div class="form-group">
  <%= label f, :title, "Title" %>
  <%= text_input f, :title, class: "form-control" %>
  <%= error_tag f, :title %>
</div>
<div class="form-group">
  <%= label f, :location, "Location" %>
  <%= text_input f, :location, class: "form-control" %>
  <%= error_tag f, :location %>
</div>
<div class="form-group">
  <%= label f, :date, "Date & Time" %>
  <%= text_input f, :date, class: "form-control", type: "datetime-local" %>
  <br>
  <%= error_tag f, :date %>
</div>
<div class="form-group">
  <%= label f, :description, "Description" %>
  <%= textarea f, :description, class: "form-control", rows: 3 %>
</div>
<%= submit "Add", class: "btn btn-primary pull-right" %>
<% end %>

apps/rsvp_web/lib/rsvp_web/templates/event/details.html.eex
<h1><%= @event.title %><small><%= @event.location %></small></h1>
<h3><%= format_date @event.date %></h3>
<h4>Available spots: <span class="quantity"> <%= @event.quantity_available %></span></h4>
<%= form_for @conn, Routes.event_path(@conn, :reserve, @event), [as: :reservation, class: "form-inline"], fn f ->  %>
<div class="form-group">
  <%= label f, :quantity, "Quantity" %>
  <%= number_input f, :quantity, class: "form-control", min: 1 %>
</div>
<%= submit "Reserve", class: "btn btn-primary pull-right" %>
<% end %>
<span id="id" data-id="<%= @event.id %>"></span>

apps/rsvp_web/lib/rsvp_web/templates/event/list.html.eex
<h1>All Events</h1>
<a href="<%= Routes.event_path(@conn, :create) %>" class="btn btn-primary pull-right">Add Event</a>
<h3>Total Count: <%= Enum.count @events %></h3>
<div class="list-group">
  <%= for e <- @events do %>
    <%= render "summary.html", event: e, conn: @conn %>
  <% end %>
</div>

apps/rsvp_web/lib/rsvp_web/templates/event/summary.html.eex
<a href="<%= Routes.event_path(@conn, :show, @event) %>">
  <div class="list-group-item">
    <h4 class="list-group-item-heading"><%= @event.title %></h4>
    <span class="text-muted"><%= @event.location %></span>
    <span class="pull-right">
      <strong><%= format_date @event.date %></strong>
    </span>
  </div>
</a>

apps/rsvp_web/lib/rsvp_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>RsvpWeb · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><a href="/">Home</a></li>
            <li><a href="<%= Routes.event_path(@conn, :list)%>">Events</a></li>
            <li><a href="<%= Routes.login_path(@conn, :index)%>">Login</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
        </nav>
        <%= if @conn.cookies["user_name"] do %>
          <span>Hello, <%= @conn.cookies["user_name"] %></span>
        <% end %>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>

apps/rsvp_web/lib/rsvp_web/templates/login/login.html.eex
<%= form_for @conn, Routes.login_path(@conn, :login), [as: :login] , fn f -> %>
<%= text_input f, :username %>
<%= submit "Login" %>
<% end %>

apps/rsvp_web/lib/rsvp_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>Peace-of-mind from prototype to production</p>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.5/CHANGELOG.md">v1.5 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on Freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
      <li>
        <a href="https://elixir-slackin.herokuapp.com/">Elixir on Slack</a>
      </li>
    </ul>
  </article>
</section>